apiVersion: v1
kind: Service
metadata:
  labels:
    app: kube-demo
  name: kube-demo
  namespace: default
spec:
  externalTrafficPolicy: Cluster
  ports:
  - nodePort: 30956
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: kube-demo
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
    - ip: 130.211.218.100